### ISSUE TITLE
All config of Email.java should be done with ParseArgs.java

### ISSUE THREAD

**Issue by freeideas** [freeideas/webx#7]
Now that ParseArgs.java can load args from a file, Email.java no longer needs to read any files for its configuration. Let's make the main method of Email.java take parms both for the construction of Email.java (e.g. username, password, imap host/port, etc) and for the operation of sending and receiving email. Email.java's main method should take everything it needs from ParseArgs. If sending, it should print something to the console like, "Email Sent to whatever@host.com". If receiving, it should print email to stdout in a way that is both human-readable, and could be parsed by a machine.

**Comment by freeideas** [comment]
🤖 CronCoder is now working on this issue.

**Comment by freeideas** [comment]
Fixed in commit 2c1250d.

Email.java has been updated to use ParseArgs for all configuration:

1. **Added parameterized constructor** that accepts all email configuration (smtp-host, imap-host, username, password, etc.)

2. **Updated main method** to accept all configuration via command-line arguments:
   - `smtp-host`, `smtp-port`, `imap-host`, `imap-port`
   - `username`, `password`, `default-from`
   - Supports loading from JSON config files using `@filename.json` syntax

3. **Maintained backward compatibility** - the no-arg constructor still uses `Lib.loadCreds()` for existing code

4. **Enhanced output format** for machine-parseable email reading:
   ```
   ===BEGIN EMAIL===
   ID: <message-id>
   From: sender@example.com
   Subject: Email subject
   Date: Tue Jan 07 10:30:00 PST 2025
   Read: true
   Content-Type: text/plain
   Body:
   Email body content...
   ===END EMAIL===
   ```

5. **Example usage**:
   ```bash
   # Send email with all parameters
   ./java/java.sh jLib.Email -command=send -smtp-host=mail.example.com -username=user@example.com -password=pass -to=recipient@example.com -subject="Hello" -body="Message"
   
   # Using config file
   ./java/java.sh jLib.Email @email-config.json -command=send -to=user@example.com -subject="Hello"
   ```

An `email-config-example.json` template has been added to demonstrate the JSON configuration format.
